### PR TITLE
Fix some Redis errors

### PR DESCRIPTION
**Pull request by AMD-NICK**
I would like to start using Redis, but I don't know where to start. May you please show me how to use it, as an alternative to this script (https://github.com/SuperiorServers/NoMultirun/blob/master/lua/autorun/server/no_multirun.lua) as an example?

### CODE REVIEW

**Comment by aStonePenguin** [comment]
you'd do something like db:Set('session_' .. pl:SteamID64(), os.time()) ect ect instead of a query. It's pretty stupid simple. Read up on redis and you should get it pretty fast.

**Comment by KingofBeast** [comment]
Broadcasting may be better than variables for NoMR. Broadcast their SteamID on CheckPassword and all connected servers should attempt to kick that SteamID. It takes maintaining session time and keeping track of active players out of the equation.

**Comment by aStonePenguin** [comment]
You can't do that @KingofBeast since they have no player object between CheckPassword and PlayerAuthed, and game.KickID() spews error when no steamid is found. You'd really be better off just setting an expiring key and using the existing implementations design.

**Comment by KingofBeast** [comment]
Hack the world #yolo @aStonedPenguin

**Comment by AMD-NICK** [comment]
@aStonedPenguin 
I am working with Redis for the first time, so I don't know how to create a DB, this is done via gmod or how?

UPD. Figured it out

**Pull request merged**
